### ISSUE TITLE
Server with Specified Hostname cannot be found.

### ISSUE THREAD

**Issue by nzraad** [pauloamgomes/drupal-react-image-gallery#1]
Hello, I am not sure if this is a Drupal my side error, but I get the following after I have completely uploaded all the images and added them to the custom react gallery. Weird how it references docker, but my instance is run off of a DigitalOcean LEMP stack.

[Error] Failed to load resource: A server with the specified hostname could not be found. (2, line 0)
[Error] Fetch API cannot load http://d8e.docker.localhost/api/image-gallery/2?_format=json. A server with the specified hostname could not be found.
[Error] TypeError: A server with the specified hostname could not be found.
	value (js_-mI9rkHVhk9XZLcFYe9_AKJvATsnTehrGB6U_wW6w3o.js:1:37444)
	Xf (react-dom.production.min.js:91:275)
	lg (react-dom.production.min.js:120:91)
	mg (react-dom.production.min.js:120:389)
	gc (react-dom.production.min.js:127:205)
	vb (react-dom.production.min.js:126:233)
	ub (react-dom.production.min.js:126)
	zd (react-dom.production.min.js:124:452)
	ra (react-dom.production.min.js:123:322)
	enqueueSetState (react-dom.production.min.js:189:234)
	setState (react.production.min.js:18:457)
	setAtomicState (js_-mI9rkHVhk9XZLcFYe9_AKJvATsnTehrGB6U_wW6w3o.js:1:45515)
	(anonymous function) (js_-mI9rkHVhk9XZLcFYe9_AKJvATsnTehrGB6U_wW6w3o.js:1:45331)
	promiseReactionJob
<img width="1378" alt="screen shot 2018-07-27 at 11 32 03 pm" src="https://user-images.githubusercontent.com/10695827/43353108-53e8552a-91f5-11e8-9b15-c88658c4ccbe.png">
<img width="869" alt="screen shot 2018-07-27 at 11 32 16 pm" src="https://user-images.githubusercontent.com/10695827/43353109-53f9a33e-91f5-11e8-9b0b-4adc8c379dd8.png">

**Comment by pauloamgomes** [comment]
Hi @nzraad , could you confirm that you can access to  http://d8e.docker.localhost/api/image-gallery/2?_format=json ?

That's a REST View that should be enabled after the module is installed.
You can try also to add d8e.docker.localhost to your /etc/hosts

**Comment by nzraad** [comment]
Yeah that still does not work. I even tried with my IP. It is worth mentioning that I am hosting this on a DigitalOcean server. So, localhost does not really work from my browser since the server is not on my computer. I am assuming that may be the issue.

**Comment by pauloamgomes** [comment]
Humm, ok, did you created an .env.local or changed the .env.production before rebuild the react component? When not testing locally you should build it with drupal host empty like below:

```
REACT_APP_DRUPAL_HOST=
```
